name: Docker Image CI

on:
  release:
    types: [released]

jobs:

  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Generate Docker metadata for Docker Hub Web
      id: metadockerweb
      uses: docker/metadata-action@v3
      with:
        images: |
          javilabs/web
        tags: |
          type=semver,pattern={{raw}}
        flavor: |
          latest=true
    - name: Generate Docker metadata for Docker Hub Getter
      id: metadockergetter
      uses: docker/metadata-action@v3
      with:
        images: |
          javilabs/getter
        tags: |
          type=semver,pattern={{raw}}
        flavor: |
          latest=true
    - name: Log into Dockerhub registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Push to Dockerhub registry web
      uses: docker/build-push-action@v2
      with:
        file: ./webd
        push: true
        tags: ${{ steps.metadockerweb.outputs.tags }}
    - name: Push to Dockerhub registry getter
      uses: docker/build-push-action@v2
      with:
        file: ./getd
        push: true
        tags: ${{ steps.metadockergetter.outputs.tags }}
